### ISSUE TITLE
Need to change some field definitions to support reporting from xdmod

### ISSUE THREAD

**Issue by rob-baron** [OCP-on-NERC/xdmod-openshift-scripts#6]
The first report will link Institution, PI, and namespace.  To make this similar to OpenStack:

    associated the group_name to the openshift_namespace
    
The second report (a nice to have) should have when someone did somethings with the resource.  Currently the who did something is missing, so:

    associated the creation/update user_name with the user_name in the record.

**Comment by joachimweyl** [comment]
As this is for OpenShift is this something for @tzumainn or is this something you plan to work on @rob-baron?

**Comment by tzumainn** [comment]
@rob-baron First, for reference, here's a table with the current mappings:

https://github.com/OCP-on-NERC/xdmod-openshift-scripts#how-it-works

Associating the group name with the openshift_namespace is easy; I just update group_name (and perhaps account_name?) to specify the openshift namespace.

The second report is more difficult, since I don't actually have that information in my query; I only have a breakdown of data by namespace. It sounds like a "nice to have" so perhaps not necessary right now?

Should I update the `user_name` field to something else regardless, since it's currently set to the openshift namespace?

**Comment by rob-baron** [comment]
We should probably set the user_name field to null (or the empty string) as we don't currently pass the data through Prometheus as to who did what (apparently).

**Comment by tzumainn** [comment]
Done!

**Comment by tzumainn** [comment]
@rob-baron thanks for the review! I've merged the update. Will you be able to get this change onto the infra cluster?

**Comment by rob-baron** [comment]
@tzumainn, the builds have been completed, check to ensure that your changes have been included.

Eventually, I plan on making this a nightly build.

**Comment by tzumainn** [comment]
I've verified that the newer data uses the updated field mapping. Thanks all!
